# Site settings
title: محمود مسیح تهرانی
email: mahmud.tehrani+jekyllblog@gmail.com
description: this is mahmoud masih tehrani weblog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://masihtehrani.github.io" # the base hostname & protocol for your site
twitter_username: mahm0ud22
github_username:  masihtehrani
paginate: 10
markdown: rdiscount
permalink: pretty
#pygments: true

# Build settings
markdown: kramdown
